// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let x=0;
let y=1;
let z=0;

for (let a; x <= 4000000 || y <= 4000000; a++) {
    
    switch (true){
        case x %2 === 0:
            z = x + z;
         break;
    }

    switch (true){
        case y %2 === 0:
            z = y + z;
        break;
    }

    x = y + x;
    y = x + y;
}

console.log(z);